### ISSUE TITLE
Draggability of Panels

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/cv-frontend-vue#56]
**Is your feature request related to a problem? Please describe.**
The Panels -
- Circuit Elements
- Properties Panel
- Timing Diagram
- Quick Panel
- Testbench
should be draggable across the canvas.
Check out the [current simulator](www.circuitverse.org) to check the drag functionality.

**Describe the solution you'd like**
Research different libraries available, compare them and find the most suitable one.
Discuss in Slack before starting to implement it.

**Are you working on this? (Yes/No)**
No

**Comment by disha1202** [comment]
Hi @devartstar,
I would like to work on this.

**Comment by palashb01** [comment]
> Hi @devartstar,
> I would like to work on this.

Hey @disha1202 , if you don't mind I would love to assist in this Issue since the Issue is big enough for an individual to apply in all 5 panels, it would be much better to breakdown the panels among two sets and apply the functionality after the final discussion.
@devartstar what do you think about this ?

**Comment by palashb01** [comment]
> Hi @devartstar,
> I would like to work on this.

Hey @disha1202 , if you don't mind I would love to assist in this Issue since the Issue is big enough for an individual to apply in all 5 panels, it would be much better to breakdown the panels among two sets and apply the functionality after the final discussion.
@devartstar what do you think about this ?

**Comment by devartstar** [comment]
Let's all first discuss the library we can use.
Then depending upon the library selected we might decide later.

I feel it won't be much hectic to implement since we are using a library. 
So for maintaining consistency is better if one person does it. So @disha1202 can pick it up I guess.

**Comment by Arnabdaz** [comment]
@disha1202 are you still working on this issue ?

**Comment by devartstar** [comment]
@Arnabdaz This issue is under hold as we still have not decided upon the library we would want to use.
Let's discuss it first in slack.

**Comment by neerajbachani** [comment]
hi @devartstar i am gsoc'2023 contributor want to work on this can you provide a slack link so that i can join :)

**Comment by SimardeepSingh1450** [comment]
@devartstar I also want to work on this issue , pls provide slack channel link for the discussion of the same .

**Comment by fillingtothemomo** [comment]
hello @Arnabdaz i would like to take up this issue

**Comment by Arnabdaz** [comment]
It's already implemented in the last Gsoc #182
